server:
  port: 8001
spring:
  application:
    name: uop
  datasource:
    url: jdbc:mysql://mysql.net:3306/uop
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: nacos.net:8848
        username: nacos
        password: ${NACOS_PASSWORD}
mybatis:
  mapper-locations: classpath:mapper/*.xml
dubbo:
  scan:
    base-packages: com.imyiren.uop
  application:
    name: uop
    registry: spring-cloud://localhost
  protocol:
    name: dubbo
    serialization: hessian2
    port: 20881
  provider:
    retries: 0
  consumer:
    timeout: 100000
    check: false
    retries: 0
  cloud:
    subscribed-services:
logging:
  level:
    org.apache.zookeeper.*: WARN
    org.apache.dubbo.*: WARN
    com.alibaba.nacos.*: WARN
