server:
  port: 8000
spring:
  profiles:
    active: local
  application:
    name: uop
  datasource:
    url: jdbc:mysql://localhost:3306/hcrm
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.apache.zookeeper.*: WARN
    org.apache.dubbo.*: WARN
